// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btgvagtoginonzowxphd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0Z3ZhZ3RvZ2lub256b3d4cGhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTMzNTksImV4cCI6MjA3MTI4OTM1OX0.ObMgoesVAlc_TECqb6AIoFHSykfV1faU4U57qMFSvNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});